== 생성자 대신 정적 팩토리 메서드의 사용을 고려하라

객체 생성을 위해 생성자 대신 정적 팩토리 메서드를 제공하는 것을 생각하라.

.정적 팩토리 메서드
[source, java]
----
public static Boolean valueOf(boolean b) {
    return b ? Boolean.TRUE : Boolean.FALSE;
}
----

=== 첫번째 이점: 이름을 가질 수 있다
생성자의 매개변수만으로는 반환되는 객체가 무엇인지 잘 설명되지 않을 경우, 정적 팩토리 메서드를 제공하여 더 이해하기 쉬운 코드를 만들 수 있다.
``BigInteger(int, int, Random)``를 예로 들 수 있다.
이 경우, 생성자만으로는 어떤 객체를 리턴해 주는지 알기 힘들지만, java 4에서 ``BigInteger.probablePrime`` 메서드가 추가되며, 이 메서드가 아마 소수를 리턴할 것이라는 것을 쉽게 알 수 있게 되었다.

번외로, 하나의 클래스에서 시그니처(메서드명, 매개변수)가 같은 메서드를 여러 개 만들 수 없다는 제약이 있다.
이러한 경우도 정적 팩토리 메서드를 사용하면 유용하다.

=== 두번째 이점: 새로운 객체를 만들 필요가 없다
불변 클래스이거나, 매번 새로운 객체를 만들 필요가 없는 클래스의 경우,
미리 만들어둔 객체를 리턴하거나 캐시되어있는 객체를 리턴하여, 불필요한 중복 객체 생성을 피할 수 있다.
``Boolean.valueOf(boolean)`` 메서드는 이를 적용하여 절대 새로은 클래스를 만들지 않는다.
이 테크닉은 ``Flyweightpattern``과 비슷하며, 객체 생성이 빈번하거나, 객체 생성에 많은 비용이 드는 경우, 이를 사용하여 성능을 향상시킬 수 있다.

=== 세번째 이점: 리턴 타입의 하위 타입 객체를 반환할 수 있다
이는 반환된 객체의 클래스를 선택할 때 큰 유연성을 제공한다.
이러한 유연성이 사용된 예로 ``java.utils.Collections`` 클래스를 들 수 있다.
이 클래스는 unmodifiable collections, synchronized collections 등 모두 45가지의 인터페이스의 구현체를 제공한다.
하지만 그 구현체들은 모두 nonpublic 이다.
이러한 방식으로 구현 클래스들을 숨기게 되면, 45개의 구현체가 모두 공개되어 있을때보다, 프로그래머가 해당 구현체들을 사용하기 위해 마스터해야 하는 개념의 수와 난이도가 줄어들게 된다.

=== 네번째 이점: 인풋 파라미터에 따라 리턴 타입이 달라질 수 있다
``EnumSet`` 클래스는 public 생성자없이, 정적 팩토리 메서드만을 가지고 있다.
``EnumSet.noneOf(...)`` 메서드는 내부적으로 원소의 개수가 64개 이하이면 ``RegularEnumSet``를 그보다 크면 ``JumboEnumSet``을 반환해준다.
``RegularEnumSet``는 원소의 개수가 적을 경우, ``JumboEnumSet``는 원소의 개수가 많을 경우 적합하기 때문인데, EnumSet을 사용하는 입장에서는 이러한 것을 고려하지 않아도 된다.
또, EnumSet 유지보수 과정에서 ``RegularEnumSet``과 ``JumboEnumSet`` 이외에 다른 구현 클래스가 추가된다고 하여도, 내부에 감춰져 있기 때문에,
기존에 사용하던 코드에는 전혀 영향을 미치지 않는다. 심지어 ``RegularEnumSet``이 제거된다고 하여도 문제가 되지 않는다.

=== 다섯번째 이점: 메서드 작성 시점에 리턴되는 객체의 클래스가 존재하지 않아도 된다
이러한 유연성을 제공하는 정적 팩토리 메서드는 Java Database Connectivity API (JDBC) 와 같은 ``service provider frameworks``에 사용된다.

