= 생성자 파라미터가 많은 경우 빌더를 고려하라
v1.0, 2020-11-16

정적 팩토리와 생성자는 많은 수의 선택적 파라미터를 받아야 할 경우 불편함이 있다. `NutritionFacts` 클래스로 예를 들어보자.
이 클래스에는 serving size, servings per container, calories per serving 의 필수 필드와 fat, cholesterol, sodium의 선택적 필드가 존재한다.

[source,java]
----
public class NutritionFacts {
    private final int servingSize;
    private final int servings;
    private final int calories;
    private int fat;
    private int cholesterol;
    private int sodium;

    public NutritionFacts(int servingSize, int servings, int calories, int fat, int cholestrerol, int sodium) {
        this.servingSize = servingSize;
        this.servings = servings;
        this.calories = calories;
        this.fat = fat;
        this.cholestrerol = cholestrerol;
        this.sodium = sodium;
    } 
}
----

== 1. 생성자를 사용할 경우

[source]
----
NutritionFacts cocaCola = new NutritionFacts(240, 8, 100, 0, 35, 27);
----

**생성자**를 사용하는 경우 사용하지 않을 파라미터를 넘겨야 하는 경우가 발생한다. (위의 경우 사용하지 않을 fat 파라미터에 0을 넘김) 물론, **Telescoping constructor** 패턴을 사용하여 해결할 수 있지만, 필드가 많아질수록 작성하기 힘들고, 알아보기 힘든 코드가 된다.

[NOTE]
====
Telescoping constructor(점층적 생성자)패턴은 필수 매개변수 한 개만 받는 생성자, 필수 매개변수와 선택적 매개 변수 한 개를 받는 생성자, 필수 매개변수 한 개와 선택적 매개변수 두 개를 받는 생성자 등의 방식으로 생성자를 늘리는 패턴이다.
====

== 2. JavaBeans 패턴을 사용할 경우

[source]
----
NutritionFacts cocaCola = new NutritionFacts();
cocaCola.setServingSize(240);
cocaCola.setServings(8);
cocaCola.setCalories(100);
cocaCola.setSodium(35);
cocaCola.setCarbohydrate(27);
----

**JavaBeans** 패턴은 가독성이 좋지만, 자체적으로 심각한 결점을 갖는다.
최종적인 구성을 위해 여러번의 호출이 필요하기 때문에, 객체 구성 과정에서 유효하지 않은 값을 가진 상태일 수 있다.
또, 불변 클래스로 사용할 수 없게 만들고, 스레드 안전성을 제공하기 위해 프로그래머의 추가적인 노력이 필요하다.

== 3. Builder 사용

`Builder` 패턴은 JavaBeans 패턴의 가독성과 Telescoping constructor 패턴의 안정성을 모두 얻을 수 있다.


[source]
----
NutritionFacts cocaCola = new NutritionFacts.Builder(240, 8)
    .calories(100)
    .sodium(35)
    .carbohydrate(27)
    .build();
----

Builder 패턴에도 단점은 존재한다. 객체를 생성하기 위해서는 먼저 빌더를 생성해야 한다는 것이다.
빌더를 생성하는 비용이 매우 작을 것 같지만, 성능이 매우 중요할 경우 문제가 발생할 소지가 있다.
또, telescoping constructor 패턴에 비해 코드 라인이 길어질 수 있기 때문에,
4개 이상의 매개변수가 존재하거나, 계속 추가될 가능성이 있는 경우 사용하는 것이 좋다.
