= 사용하지 않는 객체 레퍼런스를 제거하라
v1.0, 2020-12-17

Java에는 메모리를 관리해주는 가비지 컬렉터가 존재한다. 이로 인해 메모리 관리를 하지 않아도 된다는 생각으로 이어지기 쉽다. 하지만 이는 잘못된 생각이다. 예제를 통하여 메모리 누수가 일어날 수 있는 상황을 알아보자.

== 1. 메모리 직접 관리

[source,java]
----
// Can you spot the "memory leak"?
public class Stack {
    private Object[] elements;
    private int size = 0;
    private static final int DEFAULT_INITIAL_CAPACITY = 16;

    public Stack() {
        elements = new Object[DEFAULT_INITIAL_CAPACITY];
    }

    public void push(Object e) {
        ensureCapacity();
        elements[size++] = e;
    }

    public Object pop() {
        if (size == 0)
            throw new EmptyStackException();
        return elements[--size];
    }

    /**
    * Ensure space for at least one more element, roughly
    * doubling the capacity each time the array needs to grow.
    */
    private void ensureCapacity() {
        if (elements.length == size)
            elements = Arrays.copyOf(elements, 2 * size + 1);
    }
}
----

이 코드는 특별한 문제가 없는 것 처럼 보이지만, 메모리 누수가 발생하는 문제가 있다. 이는 가비지 컬렉션의 발생을 증가시키거나, 메모리의 사용량의 계속되는 증가로 프로그램 성능에 영향을 미칠 수 있다는 것이다. 극단적으로는 디스크 페이징, ``OutOfMemoryError``가 발생할 수도 있다.

위 코드에서 메모리 누수가 일어나는 곳은 pop 메서드이다. pop 메서드를 호출하여 반환된 오브젝트는 메모리 정리가 되지 않는다. 클라이언트에서 이 객체의 사용이 끝났어도, 스택에서는 여전히 레퍼런스를 유지하고 있기 때문에다. 이 문제를 해결하기 위해서는 다음과 같이 코드를 수정하면 된다.

[source]
----
public Object pop() {
    if (size == 0)
        throw new EmptyStackException();

    Object result = elements[--size];
    elements[size] = null; // Eliminate obsolete reference
    return result;
}
----

하지만 이것이 객체의 사용이 끝나면 항상 null로 초기화 하란 것은 아니다. **이러한 방식으로 객체의 참조를 무효화 하는것은 일반적이지 않은 예외적인 일이다.** 따라서 이를 남용해서는 안된다. 그렇다면 언제 이 방식을 사용해야 할까? 간단히 말해서 메모리를 직접 관리해야할 때 사용해야한다. 위의 Stack 구현체는 elements 배열을 갖고 있다. 이 elements에서 유효한 값들은 size 이하의 값들이다. 하지만 가비지 컬렉터는 이러한 사실을 알 지 못한다. 이 사실은 오직 프로그래머만이 알고 있으므로, 해당 레퍼런스를 null로 만들어 가비지 컬렉터에게 필요없는 객체라는 사실을 알려주어야 한다. **이처럼 ``메모리를 직접 관리``해야하는 경우, 메모리 누수를 조심해야한다.**

== 2. 캐시의 사용

**메모리 누수의 또 다른 원인은 ``캐시``를 사용할 때이다.** 우리는 객체의 레퍼런스를 캐시에 저장해 두었다가 캐시를 비우는 일을 잊어버리기 쉽다. 이러한 문제를 해결해 줄 수 있는 몇 가지 방법이 있다. ``WeakHashMap``을 사용하는 것이다. WeakHashMap은 __weak references__를 사용하여 필요 없어진 엔트리를 자동으로 Map에서 제거해준다. 하지만 WeakHashMap을 사용할 수 있는 것은 매우 제한적이다. 일반적으로, 캐시의 유효 수명을 명확히 알 수 있는 방법은 없으며, 오래된 캐시일수록 가치가 감소한다. 이러한 특성을 이용하여 오래된 캐시를 지우는 백그라운드 쓰레드를 사용하거나 (``ScheduledThreadPoolExecutor``), 캐시를 추가할 때 기존 캐시를 비우는 작업을 할 수 있다. (``LinkedHashMap``의 ``removeEldestEntry`` 메서드) 정교한 캐시 처리가 필요하다면 ``java.lang.ref``을 직접 다뤄야 할 수도 있다.

== 3. 콜백의 사용
**리스너와 콜백을 사용할 때에도 메모리 누수를 조심해야한다.** 클라이언트에서 콜백을 등록할 수 있는 API를 제공할 때, 콜백을 해제할 수 있는 방법을 제공하지 않는 경우가 있을 수 있다. 이렇게 되면 계속해서 콜백이 쌓여 문제가 생길 수 있을 것이다. 이것을 해결하기 위한 방법으로는 __weak references__를 사용하여 저장(``WeakHashMap``)하는 것이다. 메모리 누수는 발견하기가 쉽지 않아 수 년 동안 고쳐지지 않고 시스템에 남아있는 경우가 있다. 이를 발견하기 위해서는 code inspection 이나 heap profiler와 같은 디버깅 툴을 사용해야하므로, 이런 문제를 미리 예방하는 방법을 학습하여 미연에 방지하는 것이 좋다.

== 참고
https://d2.naver.com/helloworld/329631[Java Reference와 GC]