= 의존성 주입을 선호하라
v1.0, 2020-12-11

대부분의 클래스들은 하나 이상의 리소스에 의존한다.
예를 들어, SpellChecker는 dictionary에 의존한다. 이를 아래와 같이 static utility 클래스로 구현하는 모습은 흔히 볼 수 있다.

[source,java]
----
// 부적절한 static utility 사용 - 유연하지 않고 테스트 불가능
public class SpellChecker {
    private static final Lexicon dictionary = new EnglishDictionary();

    private SpellChecker() {} // Noninstantiable

    public static boolean isValid(String word) {}
    public static List<String> suggestions(String typo) {}
}
----

비슷한 예로 아래와 같은 코드도 있다.
[source,java]
----
// 부적절한 싱글톤 사용 - 유연하지 않고 테스트 불가능
public class SpellChecker {
    private final Lexicon dictionary = new EnglishDictionary();

    private SpellChecker() {}
    public static SpellChecker INSTANCE = new SpellChecker();

    public boolean isValid(String word) {}
    public List<String> suggestions(String typo) {}
}
----

의존하는 Dictionary가 하나라고 하면 위의 코드도 문제 없겠지만, EnglishDictionary 뿐 아니라 KoreanDictionary 등등 각각의 언어마다 사용해야하는 Dictionary가 다를 수 있다. 또 테스트 코드에서는 테스트용 Dictionary를 사용하고 싶을 수도 있다. 하나의 Dictionary만 사용할 거라는 가정은 너무 희망적인 생각이다. 이처럼 **리소스마다 다르게 행동하는 클래스의 경우, static utility와 싱글톤의 사용은 부적합하다.**

이러한 경우 사용할 수 있는 간단한 방법은, **생성자를 사용하여 사용할 Dictionary를 받는 것**이다. 이는 의존성 주입의 한가지 형태이다.

[source,java]
----
// 의존성 주입을 사용 - 유연하고 테스트 가능함
public class SpellChecker {
    private final Lexicon dictionary;

    public SpellChecker(Lexicon dictionary) {
        this.dictionary = Objects.requireNonNull(dictionary);
    }

    public boolean isValid(String word) {}
    public List<String> suggestions(String typo) {}
}
----

위와 같은 의존성 주입은 static factories, builders 에도 동일하게 적용할 수 있다.

이 패턴은 생성자에 resource를 생성하는 factory를 전달하는 방법으로 변형 시킬 수 있다. java 8 에서 소개된 ``Supplier<T>`` 인터페이스가 resource factory로 사용하기에 아주 적합하다. ``Supplier<T>``를 인자로 받는 메서드는 일반적으로 bounded wildcard type을 사용하여 타입을 제한한다. 예를 들면 아래의 코드와 같다.

[source]
----
Mosaic create(Supplier<? extends Tile> tileFactory) { }
----

요약하자면, 의존하는 리소스가 있고, 리소스마다 다르게 행동하는 클래스는 싱글톤이나 static utility 클래스를 사용하지 말고, 대신에 리소스나 리소스 팩토리를 생성자에 제공하여 의존성을 주입 받도록 하자는 것이다. 이렇게 하면 유연하고 재사용 가능하며 테스트 가능한 코드를 만들 수 있다.