= Friends S1 EP1

I don't want her to go throughfootnote:[go through: 겪다, 거치다] what I went through with Carl. +
_나와 칼이 겪은 일을 너가 겪고 싶게 하지 않아._

Carol moved her stuff outfootnote:[move something out: ~을 치우다, 정리하다] today. +
_캐롤이 오늘 짐을 뺐어_

Why does everyone keep fixatingfootnote:[fixate: 정착하다, 고정하다, (시선) 응시하다, 고착하다, 주의를 집중하다]footnote:[keep + 동사 ing: 계속해서 ~하다] on that? +
_왜 다들 그것에 집착하는거지?_

I realized that I was more turned on byfootnote:[be terned on by (something / somebody): ~에 의해 (성적으로) 흥분되다, 설레다] this gravy boat than Barry. +
_나는 배리보다 이 소스 그릇에 더 설렌다는 사실을 깨달았어_

I got really freaked outfootnote:[freak out: 기겁하다, 깜짝 놀라다, (정신적으로) 충격받다]. +
_정말 충격적이었어_

I started wondering 'Why am I doing this, and who am I doing this for?' +
_나는 의아해하기 시작했어 '내가 이걸 왜 하고 있는지, 그리고 나는 누글 위해 이걸 하고 있는지'_

I know that you and I have kind of drifted apartfootnote:[drift apart (from each other): (점점) 사이가 멀어지다]. +
_우리 사이가 멀어졌다는 걸 알아_

Just try to think offootnote:[think of: ~을 생각하다] nice calm things. +
_그냥 기분 좋고 잔잔한 것들을 떠올려 봐_

This is probably for the bestfootnote:[be (all) for the best: (지금은 안 좋은 것 같지만) 결국엔 잘 될 것이다, 이게 최선이다], you know? +
_결국엔 잘 될거야_

He finally asked you outfootnote:[ask (somebody) out: ~에게 데이트를 신청하다]? +
_그가 마침내 너에게 데이트 신청을 했어?_

Ooh, I just pulled outfootnote:[pull (something) out: (일반적으로 힘을 가하여 어떤 것을) 제거하다] four eyelashes. +
_오, 방금 속눈썹 네 개를 뽑아버렸어_

I was kind of supposed to befootnote:[be supposed to do / be something: (원래는) ~하기로 되어있었다, ~해야한다, (일반적으로) ~인 것으로 여겨진다] headedfootnote:[be headed for (a place): ~로 가다, 향하다] for Aruba on my honeymoon, so nothing. +
_신혼여행으로 아루바에 가려고 했었는데, 그러니까 (할 일이) 없어._

I'm supposed to attach a brackety thing to the side things +
_원래 이 브라켓 같은 것을 옆 판때기 같은 것들에 부착해야 돼_

She always drank it out offootnote:[drink (something) out of ~: ~로 ~를 마시다] the can. +
_그녀는 항상 이것을 캔 채로 마셨어_

I guess I should have caughtfootnote:[should have p.p: ~했어야 했다(하지 않았다)] onfootnote:[catch on: 이해하다, 알아채다, 인지하다] when she started going to the dentist four and five times a week +
_그녀가 일주일에 네다섯번씩 치과에 가기 시작했을때 눈치 챘어야 했어_

You know what the scariest part is? +
_너희들 가장 두려운 부분이 뭔지 알아?_

Ever sincefootnote:[ever since: ~이후로 계속] she walked out onfootnote:[walk out on (somebody): ~를 (버리고) 떠나다] me, I... +
_그녀가 나를 버리고 떠난 후로 줄곧, 난..._

Do you know how long it's been since I've grabbed a spoon? +
_너희들 내가 숟가락을 잡은지 얼마나 오래됐는지 알아?_

I have never madefootnote:[have never p.p: 해 본 적이 없다. / have not p.p: 하지 않았다] coffee before in my entire life. +
_난 내 생에 커피를 만들어 본적이 없어_

We all have jobs. See, that's how we buy stuff. +
_우리는 모두 직업이 있어. 그게 물건을 살 수 있는 방법이지_

You can't live offfootnote:[live off somebody / something: ~의 (경제적) 도움으로 살다, ~에 의지해서 살다] your parents whole your life. +
_평생 부모님께 의지해서 살 수는 없어_

Give her a breakfootnote:[give somebody a break: ~에게 기회를 주다, ~를 너그럽게 봐주다], it's hard being on your ownfootnote:[own one's own: 혼자서, 자력으로] for the first time. +
_그녀 좀 봐줘, 처음으로 홀로서는 것은 힘들어._

You just put it backfootnote:[put it back: 원래 있던 자리에 갖다 놓다] where you found it. +
_그냥 그거 찾았던 곳에다가 다시 둬_