= Zootopia #1

https://www.youtube.com/watch?v=qzR3ESi8ReU&t=76s[주토피아 #1]

== 대사

Stu Hopps: Well, we gave up on our dreams and we settled, right, Bon? +
_우리는 원래의 꿈을 포기하고 정착했단다. 그렇지 여보?_

Bonnie Hopps: Oh, yes, that's right, Stu. We settled hard. +
_네 맞아요. 완전 정착했죠._

Stu Hopps: See? That's the beauty of complacency, Jude. If you don't try anything new, you'll never fail! +
_들었지? 현실에 안주한다는 건 이렇게 멋진 거란다 주디. 새로운 걸 하려고 하지 않으면, 절대 실패할 일이 없어._

Young Judy Hopps: I like trying, actually. +
_저는 시도하는 걸 좋아하는데요._

Bonnie Hopps: What your father means, hun, is that it's gonna be difficult, impossible even, for you to become a police officer. +
_아빠 말의 의미는, 경찰이 되는 것은 어렵다는 거야. 어쩌면 불가능할 지도 몰라._

Stu Hopps: Right! There's never been a bunny cop. +
_맞아, 토끼 경찰관은 한번도 본 적이 없단다._

Bonnie Hopps: No.

Stu Hopps: Bunnies don't do that.

Bonnie Hopps: Never!

Stu Hopps: Never.

Young Judy Hopps: Oh... Then I guess I'll have to be the first one! Because I am gonna make the world a better place! +
_아, 그럼 제가 토끼중에서는 처음으로 경찰관이 될 거예요. 저는 더 좋은 세상을 만들고 싶거든요._

Stu Hopps: Or, uh, heck, you know, if you wanna talk about making the world a better place, no better way to do it than becoming a carrot farmer. +
_아니면, 뭐, 정 세상을 더 좋은 곳으로 만들고 싶다면, 당근 농사 만큼 좋은 건 없단다._

Bonnie Hopps: Yes! Your dad, me, your two-hundred seventy-five brothers and sisters, we're changing the world! +
_그래! 너의 아빠와 나, 265명의 형제 자매들, 우리는 세상을 변화시키는 중이란다._

Stu Hopps: Yeah.

Bonnie Hopps: One carrot at a time!

Stu Hopps: Amen to that. Carrot farming is a noble profession. +
_완전 동의해. 당근 농사는 고귀한 직업이야._

== 유용한 표현

1. See? *That's the beauty of* complacency, Jude. +
그게 ~의 장점이야

2. Right! *There's never been a* bunny cop. +
There has been -> There is의 변형 형태로 과거부터 현재까지 쭉 있어왔다는 뜻
