= Zootopia #1

https://www.youtube.com/watch?v=tqkWQwi2Su0&list=PLYNja5Mm_Ma7udPS4Ujcqfhm8MQHdsHCi&index=27[주토피아 #2]

== 대사

Young Gideon Grey: Gimme your tickets right now, or I'm gonna kick your meek little sheep butt! +
_당장 티켓을 내놓지 않으면 너의 엉덩이를 걷어 차 버릴거야!_

Sharla: Ow! Cut it out, Gideon! +
_이러지 마 기디온!_

Young Gideon Grey: Baaa, baaa! What are you gonna do, cry? +
_음매, 음매! 어떻게 하려고, 울려고?_

Young Judy Hopps: Hey! You heard her, cut it out. +
_이봐! 쟤 말 들었잖아. 그만하라고._

Young Gideon Grey: Nice costume, loser! What crazy world are you livin' in where you think a bunny could be a cop? +
_제복은 멋있네, 찌질아! 어떤 미친 세상에 사는거야, 토끼가 경찰이 될 수 있다고 생각하다니_

Young Judy Hopps: Kindly return my friend's tickets. +
_내 친구의 티켓을 돌려주겠니?_

Young Gideon Grey: Come and get 'em! But watch out, 'cause I'm a fox, and like you said in your dumb little stage play, us predators used to eat prey! And our killer instinct's still in our duh-nuh. +
_가져가 봐. 그렇지만 조심해 나는 여우거든. 너가 그 작고 멍청한 무대에서 말했듯이, 예전에 우리 육식 동물들은 먹이를 잡아 먹었다고. 그리고 아직까지 그 피가 우리 더나아에 흐르거든._

Travis: Uh, I'm pretty much sure it's pronounced D-N-A. +
_그건 디엔에이라고 발음하는 게 맞아._

Young Gideon Grey: Don't tell me what I know, Travis! +
_나도 알아 트래비스_

Young Judy Hopps: You don't scare me, Gideon! +
_난 너한테 겁먹지 않아, 기디온_

Young Gideon Grey: Scared now? +
_이제 겁이나지?_

Travis: Look at her nose twitch! She is scared! +
_코 씰룩이는 것 좀 봐. 겁먹었어!_

== 유용한 표현

Hey! You heard her, *cut it out*. +
누군가를 놀리거나 짖굳은 장난을 할 때 "그만해"라는 의미로 자주 사용. 비슷한 표현으로 knock it off 라는 표현이 있음.

*Kindly* return my friend's tickets. +
명령문 앞에 쓰게되면 부드럽고 정중한 표현이 됨.